# Permalinks
permalink:        pretty

# Setup
url:              http://lsr90518.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            FluffyLiu

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  读书笔记，技术博客，欢迎与我交流，互动。
  lb90518@gmail.com.

# The tags listed as entries in the sidebar
sidebar_tags:     [tech, review]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           '刘松然'
  github:         lsr90518
  photo:          https://avatars0.githubusercontent.com/u/4392072?v=3&s=460

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:

gems:
  - jekyll-seo-tag